name: gan-genai-linux-20241224
channels:
  # - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib

  - pip:
    - "tensorflow[and-cuda]==2.13"
    - "keras==2.13.*"
    - tensorrt
    - tensorrt_lean
    - tensorrt_dispatch
    - torch
    - torchvision
    - torchaudio
