name: ggl-colab-genai-winos-20241208
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python=3.10.12
  
  # Core Conda dependencies
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - ipython
  - jupyterlab
  - tensorflow=2.17
  - pytorch::pytorch=2.5  # Using PyTorch channel for CUDA-enabled PyTorch
  - torchvision
  - torchaudio
  - flask
  - requests
  - transformers
  - huggingface_hub
  - nltk
  - spacy
  - tensorflow-probability
  - xgboost

  # Additional dependencies that aren't available via Conda
  - pip:
      - cudf-cu12 @ https://pypi.nvidia.com/cudf-cu12/cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
      - nx-cugraph-cu12 @ https://pypi.nvidia.com/nx-cugraph-cu12/nx_cugraph_cu12-24.10.0-py3-none-any.whl
      - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl#sha256=86cc141f63942d4b2c5fcee06630fd6f904788d2f0ab005cce45aadb8fb73889
      - torch==2.5.1+cu121 @ https://download.pytorch.org/whl/cu121_full/torch-2.5.1%2Bcu121-cp310-cp310-linux_x86_64.whl
      - torchaudio==2.5.1+cu121 @ https://download.pytorch.org/whl/cu121/torchaudio-2.5.1%2Bcu121-cp310-cp310-linux_x86_64.whl
      - torchvision==0.20.1+cu121 @ https://download.pytorch.org/whl/cu121/torchvision-0.20.1%2Bcu121-cp310-cp310-linux_x86_64.whl
